#!/bin/sh
INPUT=$1
FILENAME=$2
SIZE=$3
truncate -s $SIZE $FILENAME
mkfs.ext4 $FILENAME
mkdir -p data
sudo mount -o loop $FILENAME data
sudo tar -xvf $INPUT -C data
sudo sync
sudo umount data
rmdir data
