#!/bin/sh

fallocate -l 1M /tmp/sysboot.img0
dd bs=440 count=1 conv=notrunc if=/usr/lib/syslinux/bios/mbr.bin of=/tmp/sysboot.img0

fallocate -l 1023M /tmp/sysboot.img1
mkfs.vfat -F 32 -n BOOT /tmp/sysboot.img1
mmd -i /tmp/sysboot.img1 ::syslinux
mcopy -i /tmp/sysboot.img1 /usr/lib/syslinux/bios/*.c32 ::syslinux/
mcopy -i /tmp/sysboot.img1 /boot/syslinux/syslinux.cfg ::syslinux/
mcopy -i /tmp/sysboot.img1 /boot/syslinux/splash.png ::syslinux/
syslinux --directory syslinux --install /tmp/sysboot.img1

touch /tmp/sysboot.img
dd if=/tmp/sysboot.img0 of=/tmp/sysboot.img bs=1M oflag=append conv=notrunc
dd if=/tmp/sysboot.img1 of=/tmp/sysboot.img bs=1M oflag=append conv=notrunc

sfdisk /tmp/sysboot.img <<EOF
label: dos
label-id: 0x43c60e30
device: sysboot.img
unit: sectors

sysboot.img1 : start=        2048, size=     2095104, type=b, bootable
EOF
